/**
 * LocalPlayer mock padrão - dados típicos Tibia ao entrar no jogo.
 * Equivalente ao que o OTClient recebe do servidor (ProtocolGame).
 */
export const DEFAULT_PLAYER = {
  name: 'Player',
  level: 8,
  baseLevel: 8,
  experience: 4200,
  expSpeed: 0,
  health: 155,
  maxHealth: 155,
  mana: 60,
  maxMana: 60,
  soul: 100,
  freeCapacity: 1000,
  totalCapacity: 1000,
  speed: 110,
  baseSpeed: 110,
  stamina: 42 * 60,
  offlineTrainingTime: 0,
  regenerationTime: 0,
  magicLevel: 1,
  magicLevelPercent: 10,
  baseMagicLevel: 1,
  isPremium: false,
  skills: {
    0: { level: 10, percent: 0, baseLevel: 10 },
    1: { level: 10, percent: 0, baseLevel: 10 },
    2: { level: 10, percent: 0, baseLevel: 10 },
    3: { level: 10, percent: 0, baseLevel: 10 },
    4: { level: 10, percent: 0, baseLevel: 10 },
    5: { level: 10, percent: 0, baseLevel: 10 },
    6: { level: 10, percent: 0, baseLevel: 10 },
    7: 0,
    8: 0,
    9: 0,
    10: 0,
    11: 0,
    12: 0,
    13: 0,
    14: 0,
    15: 0,
    16: 0,
  },
  offence: { flatDamageHealing: 0, attackValue: 0, attackElement: 0, convertedDamage: 0, convertedElement: 0, lifeLeech: 0, manaLeech: 0, critChance: 0, critDamage: 0, onslaught: 0 },
  defence: { defense: 0, armor: 0, mitigation: 0, dodge: 0, damageReflection: 0, combatAbsorbValues: {} },
  misc: { momentum: 0, transcendence: 0, amplification: 0 },
}
